title:              "friendly-oh"
title2:             "ʕっ•ᴥ•ʔっ"
email:              your-email@example.com
description:        "반갑습니다. 개발자를 꿈꾸는 오세준입니다."
author:             SejunO
baseurl:            ""
url:                "https://sejunO.github.io"

# Social Profiles
twitter_username:   
github_username:    sejunO
facebook_username:  
instagram_username:  o_sae__
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
        input :     GFM
        syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
